export default {
    printWidth: 120,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'as-needed' as 'as-needed',
    jsxSingleQuote: true,
    trailingComma: 'all' as 'all',
    bracketSpacing: false,
    bracketSameLine: false,
    jsxBracketSameLine: false,
    arrowParens: 'avoid' as 'avoid',
    proseWrap: 'never' as 'never',
    htmlWhitespaceSensitivity: 'ignore' as 'ignore',
    endOfLine: 'lf' as 'lf',
    embeddedLanguageFormatting: 'off' as 'off',
    singleAttributePerLine: false,
    plugins: [],
    // xmlSelfClosingSpace: true,
    // xmlWhitespaceSensitivity: 'strict',
};
