import rules from './rules';

exports = {
    extends: [],
    ignoreFiles: ['node_modules/**', 'dist/**', 'coverage/**', 'output/**'],
    plugins: ['stylelint-order'],
    rules: {
        ...rules,
        'scss/at-each-key-value-single-line': true,
        'scss/at-else-closing-brace-newline-after': 'always-last-in-chain',
        'scss/at-else-closing-brace-space-after': 'always-intermediate',
        'scss/at-else-empty-line-before': 'never',
        'scss/at-else-if-parentheses-space-before': 'always',
        'scss/at-extend-no-missing-placeholder': true,
        'scss/at-function-named-arguments': 'always',
        'scss/at-function-parentheses-space-before': 'always',
        // 'scss/at-function-pattern': '',
        'scss/at-import-no-partial-leading-underscore': true,
        'scss/at-import-partial-extension': 'always',
        // 'scss/at-import-partial-extension-blacklist': ['scss', /less/],
        // 'scss/t-import-partial-extension-whitelist': ['scss', /less/],
        'scss/at-mixin-argumentless-call-parentheses': 'always',
        'scss/at-mixin-named-arguments': 'always',
        'scss/at-mixin-parentheses-space-before': 'always',
        // 'scss/at-mixin-pattern': '',
        // 'scss/at-rule-conditional-no-parentheses': true,
        // 'scss/at-rule-no-unknown': true,
        'scss/dollar-variable-colon-newline-after': 'always-multi-line',
        'scss/dollar-variable-colon-space-after': 'always',
        'scss/dollar-variable-colon-space-before': 'never',
        'scss/dollar-variable-default': [true, {ignore: 'local'}],
        'scss/dollar-variable-empty-line-after': [
            'always',
            {
                except: ['last-nested', 'before-comment', 'before-dollar-variable'],
            },
        ],
        'scss/dollar-variable-empty-line-before': [
            'always',
            {
                except: ['first-nested', 'after-comment', 'after-dollar-variable'],
            },
        ],
        'scss/dollar-variable-first-in-block': [
            true,
            {
                ignore: ['comments', 'imports'],
                except: ['root', 'at-rule', 'function', 'mixin', 'if-else', 'loops'],
            },
        ],
        'scss/dollar-variable-no-missing-interpolation': true,
        // 'scss/dollar-variable-pattern':/^-/,
        // 'scss/double-slash-comment-empty-line-before': 'always',
        // 'scss/double-slash-comment-inline': 'never',
        'scss/double-slash-comment-whitespace-inside': 'always',
        'scss/comment-no-empty': true,
        // 'scss/comment-no-loud': true,
        'scss/declaration-nested-properties': 'never',
        'scss/declaration-nested-properties-no-divided-groups': true,
        'scss/dimension-no-non-numeric-values': true,
        // 'scss/function-color-relative': true,
        'scss/function-quote-no-quoted-strings-inside': true,
        // 'scss/map-keys-quotes': true,
        'scss/media-feature-value-dollar-variable': 'always',
        // 'scss/operator-no-newline-after': true,
        // 'scss/operator-no-newline-before': true,
        'scss/operator-no-unspaced': true,
        'scss/selector-nest-combinators': 'always',
        'scss/selector-no-redundant-nesting-selector': true,
        // 'scss/selector-no-union-class-name': true,
        'scss/no-duplicate-dollar-variables': true,
        'scss/no-duplicate-mixins': true,
        'scss/no-global-function-names': true,
    },
};
